### PR TITLE
rework of recipeForm to improve stability

### PR DESCRIPTION
**Pull request by FlanFlanagan**
Fixes the recipe view.  Also some minor tweeks for style.

### CODE REVIEW

**Comment by gidden** [comment]
hi @FlanFlanagan, can you tell me what was broken before so I can test to make sure it works on my end?

**Comment by FlanFlanagan** [comment]
Some save and load issues mostly. Also fixes some confusion in how to use it.

**Comment by gidden** [comment]
some notes from my just playing around

- you can "add recipe" on an empty recipe and it gets logged in the select recipe filter (but it's not clickable)

f

**Comment by gidden** [comment]
sigh it doesn't show up in this screenshot

**Comment by gidden** [comment]
Basically, you can add "unnamed" recipes, which get logged in the list of recipes. They stay there, but are not selectable after.

**Comment by gidden** [comment]
You can test this yourself by just clicking "add recipe" on an empty dialogue box a few times

**Comment by gidden** [comment]
also, it looks like recipes are still having conversion issues with adding some small value to them (~2e-8). For example, I loaded the cycic tutorial file and added a recipe with 6.5% U235 and get the following:
```
$ cat foo.xml | grep -C 2 235
    <basis>mass</basis>
    <nuclide>
      <id>92235</id>
      <comp>0.0070002</comp>
    </nuclide>
--
    <basis>mass</basis>
    <nuclide>
      <id>u-235</id>
      <comp>0.0400002</comp>
    </nuclide>
--
    <basis>mass</basis>
    <nuclide>
      <id>u-235</id>
      <comp>0.0110002</comp>
    </nuclide>
--
    <basis>atom</basis>
    <nuclide>
      <id>u-235</id>
      <comp>6.5000002</comp>
    </nuclide>
```

**Comment by gidden** [comment]
I fixed that issue in 60f97c9

**Comment by gidden** [comment]
it looks like the add recipe issue is going to be complex to fix, I'll make an issue and not let it block this PR

**Comment by gidden** [comment]
hi @FlanFlanagan, I've made some additional improvements. care to test drive them?

**Comment by FlanFlanagan** [comment]
I'll give them a look at now.

**Comment by FlanFlanagan** [comment]
@gidden  I've made changes that piggy back off yours. Basically shifted the add recipe button is a more intuitive place (I think).

**Comment by gidden** [comment]
Ok, I don't know what changes the isotope datastructures introduced, so I can't comment on them. I'm neutral on the button position change.

**Comment by gidden** [comment]
hi @FlanFlanagan, this looks like it includes changes to the `addIsotope` method, but that method is no longer used? 

Would you mind if we fixed up the last two commits to only include the placement update?

**Comment by FlanFlanagan** [comment]
That's fine. I can do that. I could also just remove addIsotope, it is no longer used. I think that change made it possible to have the button where it is. So, probably best to just remove addIsotope. Or just remove that commit.

**Comment by gidden** [comment]
Either one of us could. My suggested workflow would be:

- revert previous two commits
- make a single commit that is only the placement change
- (optional) make a commit that removes the addisotope function
- git push -f upstream minor_fixes

Let me know what you prefer

On Tue, Jul 14, 2015 at 10:46 AM, FlanFlanagan <notifications@github.com>
wrote:

> That's fine. I can do that. I could also just remove addIsotope, it is no
> longer used. I think that change made it possible to have the button where
> it is. So, probably best to just remove addIsotope. Or just remove that
> commit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/pull/144#issuecomment-121286445>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Pull request merged**
