### PR TITLE
Pastels

### PR DESCRIPTION
**Pull request by gonuke**
This transforms the colors generated through stringToColor through HSB space to force a brightness of 1.0 and limit the saturation to (0.4,0.7).

These values are kind of a guess, but it seems to result in a nice palette.

I've only applied it to the archetype ribbons so far.

### CODE REVIEW

**Comment by gidden** [comment]
looks like this might need a rebase @gonuke

**Comment by gonuke** [comment]
Note that even after merging this, we can easily change the parameters in the pastelize() method to recover the current colors.

**Comment by gonuke** [comment]
Rebased following #42

**Comment by gidden** [comment]
looks good

**Pull request merged**
