### PR TITLE
Fix def skin

### LINKED ISSUE #58: choosing DSARR as the default skin before DnD of archetypes gives empty space
I set the skin to DSARR before dragging any archetypes into the pane and it appeared as though nothing happened.  When I toggled back to default/DSARR again, it came back fine.

### PR DESCRIPTION
**Pull request by gonuke**
Fixes #58 by pulling a default skin imag when necessary

### CODE REVIEW

**Comment by gidden** [comment]
I get a merge conflict on the current v1.3.0-release branch

**Comment by gonuke** [comment]
This now does only 1 thing - adds a "separations" niche to support the v1.3.0 separations in cycamore.

I think I saw a PR to remove this niche:separations from Separations... but can't find it

**Comment by gonuke** [comment]
should be ready to go, btw

**Comment by gidden** [comment]
looks good

**Pull request merged**
