### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by FlanFlanagan**

### CODE REVIEW

**Comment by gidden** [comment]
hey @FlanFlanagan, do you want to keep working on this branch until we get everything done? or do you want to merge this and work on a different branch?

**Comment by FlanFlanagan** [comment]
Develop is good


On Wed, May 20, 2015 at 11:05 AM, Matthew Gidden <notifications@github.com>
wrote:

> hey @FlanFlanagan <https://github.com/FlanFlanagan>, do you want to keep
> working on this branch until we get everything done? or do you want to
> merge this and work on a different branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/pull/17#issuecomment-103940964>.
>



-- 
Robert Flanagan
Graduate Research Assistant
Nuclear and Radiation Engineering Program
Department of Mechanical Engineering
The University of Texas at Austin

**Comment by gidden** [comment]
@FlanFlanagan, can this be closed?

**Comment by FlanFlanagan** [comment]
I think so, not sure which this is

**Pull request closed without merging**
