### PR TITLE
you can now add an institution via the add button on the top banner, …

### PR DESCRIPTION
**Pull request by gidden**
…this was broken before

modeled after the `addRegion`

just as a note, the different corral views could definitely be combined into a single base class with some derived specialization as needed.

### CODE REVIEW

**Comment by gidden** [comment]
this PR actually breaks things badly and in an unexpected way if the "feature" is used

specifically, add an inst using the top banner
click "generate"
see the error reported in #109 

any ideas @FlanFlanagan?

**Comment by gidden** [comment]
I believe I have fixed the issue now. @FlanFlanagan, this still places the inst oval outside of the corral bounding box. The previous fix required knowing where the user clicked. I'm not sure how to fix that here.

**Comment by FlanFlanagan** [comment]
instituteNode.institutionShape.setCenterX(someValue)
instituteNode.institutionShape.setCenterY(someValue)
VisFunctions.placeTextOnEllipse(instituteNode.institutionShape, "middle")

**Comment by FlanFlanagan** [comment]
This also needs to be update to work for the region as well if you get time. That is also broken in the same way.

**Comment by gonuke** [comment]
Where someValue is calculated by getting the geom of the pane and place it at the center or such...

**Comment by FlanFlanagan** [comment]
someValue  = 150 should work.

**Comment by gidden** [comment]
updated and fixed for regions

**Comment by FlanFlanagan** [comment]
Looks good. I'm going to merge.

**Pull request merged**
