### PR TITLE
updated niche issues and changed prototype menu

### PR DESCRIPTION
**Pull request by FlanFlanagan**

### CODE REVIEW

**Comment by gidden** [comment]
@FlanFlanagan, what issues does this PR address?

also, you may find it more convenient to use feature branches so you can do more work on your end (rather than doing everything on develop). Just a thought!

**Comment by FlanFlanagan** [comment]
Oh, it basically lets the users manual put in the niche of the prototype if they want to change it. It also changes the prototypes menuBar to a contextMenu (the newer better option)

**Comment by FlanFlanagan** [comment]
And yeah. I was going to make a feature branch for this but I was in a groove and just sort of keep going. 

I will in the future! thanks!

**Comment by gidden** [comment]
looks good

**Pull request merged**
