### PR TITLE
Add entry for lifetime on every facility at userlevel > 0

### PR DESCRIPTION
**Pull request by gonuke**
my first PR from 30,000 ft!

### CODE REVIEW

**Comment by gonuke** [comment]
The only thing missing is that I don't test that it's an integer, which the schema probably expects?

**Comment by FlanFlanagan** [comment]
Looks good Paul. We can probably add the integer check after? Or we can use my number only text field for this as well.

**Comment by gonuke** [comment]
Can you point me to the number only text field?

**Comment by FlanFlanagan** [comment]
I thought I extended the class but I guess not. 

This code should do the trick when building the text field. 

			TextField isoWeightFrac = new TextField(){
				@Override public void replaceText(int start, int end, String text) {
					if (!text.matches("[a-z]")){
						super.replaceText(start, end, text);
					}
				}
				
				public void replaceSelection(String text) {
					if (!text.matches("[a-z]")){
						super.replaceSelection(text);
					}
				}
			};

**Comment by FlanFlanagan** [comment]
sorry that bottom bit of code is superfluous. Just need 

        TextField isoWeightFrac = new TextField(){
            @Override public void replaceText(int start, int end, String text) {
                if (!text.matches("[a-z]")){
                    super.replaceText(start, end, text);
                }
            }
        };

**Comment by gonuke** [comment]
hold on whitespace....

**Comment by gonuke** [comment]
whitespace updated...

**Comment by FlanFlanagan** [comment]
Is this ready paul?

**Comment by gonuke** [comment]
one sec... switching to context menus as part of this

**Comment by gonuke** [comment]
ready now

**Comment by gonuke** [comment]
crap!! wrong PR  hold on

**Comment by gonuke** [comment]
Nope.. it's OK.  You already merged #111.  The last few commits are more related to that, so this should be good to go on top of that merge.

**Pull request merged**
