### PR TITLE
removing a one or more now updates commodities lists

### PR DESCRIPTION
**Pull request by FlanFlanagan**

### CODE REVIEW

**Comment by gidden** [comment]
I set up a simulation with two sources, one for commodity c and one for d, with a sink that takes both, and have tried the following:

- remove commodity d: still in source list, still in sink list, but arrow is removed
- re-add commodity d: arrow not reinstated

I suppose I don't understand what is the PR supposed to do?

**Comment by FlanFlanagan** [comment]
can you show me the behavior. 

This PR lets you remove a onOrMore field with a commodity somewhere inside it and the Pane should reflect the removal of the commodity.

**Comment by gidden** [comment]
Hi Radio,

I think this is really close to solving the problem. I see that now removal happens if I explicitly click the "remove" button. Removal does *not* happen if I "remove" the commodity by changing the drop box. I think the best way to try this is the following pseudo code:
```
if commodity changes via drop down box:
    if commodity does not exist in other list (as another drop-down box entry):
        remove commodity connections
```

**Comment by FlanFlanagan** [comment]
It's more complex than that, but I see the problem.

**Comment by FlanFlanagan** [comment]
Need a set of eyes on this, it's been updated to fix the bug matt encountered.

**Comment by gidden** [comment]
If I remove commodities from the list on the left, they still stay on the agents.

**Comment by FlanFlanagan** [comment]
Oh sorry, I meant a different bug. This PR was not meant for the list on the left. But I'll just put that code into this PR instead of making a new one.

**Comment by gidden** [comment]
ok. while this would be a nice fix to have I'm not sure how much work it will take and where it ranks on our triage list. perhaps @gonuke can offer an opinion.

**Comment by FlanFlanagan** [comment]
Oh, so I have the underlying code working. I just need to get it to redraw the formBuidlers, which I'm working on now. Currently if you close the form and reopen it the change is reflected, but now live.

**Comment by FlanFlanagan** [comment]
er not live*

**Comment by gonuke** [comment]
Does this last commit make this ready for review?

**Comment by gonuke** [comment]
This looks like it does what we need for now.  Removing the commodity from open comboBoxes will require more effort that we currently have time for.

**Comment by FlanFlanagan** [comment]
Unfortunately I agree with that. If I get a chance I will take a stab today but no promises.

**Comment by gonuke** [comment]
No - I don't think we should be taking stabs at anything now.  There is too much chance that other new things emerge and we need to keep the docket clear fr that. 

I'll merge this and we can just make an issue for later.

**Comment by FlanFlanagan** [comment]
Aye aye

**Pull request merged**
